// ── 错误码常量（与 Python error_codes.py 对齐）──────────────

// 加载阶段
export const CERT_NOT_FOUND = 'CERT_NOT_FOUND';
export const CERT_PARSE_ERROR = 'CERT_PARSE_ERROR';
export const CERT_EXPIRED = 'CERT_EXPIRED';
export const CERT_NOT_YET_VALID = 'CERT_NOT_YET_VALID';
export const CERT_CHAIN_BROKEN = 'CERT_CHAIN_BROKEN';
export const KEYPAIR_MISMATCH = 'KEYPAIR_MISMATCH';
export const PRIVATE_KEY_PARSE_ERROR = 'PRIVATE_KEY_PARSE_ERROR';

// 注册阶段
export const IDENTITY_CONFLICT = 'IDENTITY_CONFLICT';
export const INVALID_AID_FORMAT = 'INVALID_AID_FORMAT';
export const NETWORK_ERROR = 'NETWORK_ERROR';
export const SERVER_ERROR = 'SERVER_ERROR';

// agent.md / 证书下载阶段
export const AGENTMD_NOT_FOUND = 'AGENTMD_NOT_FOUND';
export const AGENTMD_PARSE_ERROR = 'AGENTMD_PARSE_ERROR';
export const SIGNATURE_NOT_FOUND = 'SIGNATURE_NOT_FOUND';
export const SIGNATURE_INVALID = 'SIGNATURE_INVALID';
export const CERT_FINGERPRINT_MISMATCH = 'CERT_FINGERPRINT_MISMATCH';

// 证书运维阶段
export const CERT_RENEWAL_FAILED = 'CERT_RENEWAL_FAILED';
export const REKEY_FAILED = 'REKEY_FAILED';
export const PRIVATE_KEY_REQUIRED = 'PRIVATE_KEY_REQUIRED';

// 密码学操作
export const SIGNATURE_OPERATION_ERROR = 'SIGNATURE_OPERATION_ERROR';
export const VERIFICATION_OPERATION_ERROR = 'VERIFICATION_OPERATION_ERROR';
export const CERT_NOT_VALID = 'CERT_NOT_VALID';
export const PRIVATE_KEY_NOT_VALID = 'PRIVATE_KEY_NOT_VALID';

export const TRUST_ROOTS_INVALID = 'TRUST_ROOTS_INVALID';
