from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol


class TokenStore(Protocol):
    """不含私钥操作的存储接口，AuthFlow / AUNClient 持有此类型。

    包含：证书、token/实例状态、seq、群组状态、metadata、agent.md 缓存、
    信任根等所有非私钥操作。
    """

    def load_cert(self, aid: str, cert_fingerprint: str | None = None) -> str | None: ...

    def save_cert(
        self,
        aid: str,
        cert_pem: str,
        cert_fingerprint: str | None = None,
        *,
        make_active: bool = True,
    ) -> None: ...

    def load_metadata(self, aid: str) -> dict[str, Any] | None: ...

    def get_metadata_value(self, aid: str, key: str) -> str: ...

    def set_metadata_value(self, aid: str, key: str, value: str) -> None: ...

    def load_instance_state(self, aid: str, device_id: str, slot_id: str = "") -> dict[str, Any] | None: ...

    def save_instance_state(self, aid: str, device_id: str, slot_id: str, state: dict[str, Any]) -> None: ...

    def update_instance_state(
        self,
        aid: str,
        device_id: str,
        slot_id: str,
        updater: Callable[[dict[str, Any]], dict[str, Any] | None],
    ) -> dict[str, Any]: ...

    def save_seq(self, aid: str, device_id: str, slot_id: str, namespace: str, contiguous_seq: int) -> None: ...

    def load_seq(self, aid: str, device_id: str, slot_id: str, namespace: str) -> int: ...

    def load_all_seqs(self, aid: str, device_id: str, slot_id: str) -> dict[str, int]: ...

    def delete_seq(self, aid: str, device_id: str, slot_id: str, namespace: str) -> None: ...


class KeyStore(Protocol):
    """私钥/完整身份存储接口，仅 AIDStore / RegisterFlow 持有。"""

    def load_key_pair(self, aid: str) -> dict | None: ...

    def save_key_pair(self, aid: str, key_pair: dict) -> None: ...

    def load_cert(self, aid: str, cert_fingerprint: str | None = None) -> str | None: ...

    def save_cert(
        self,
        aid: str,
        cert_pem: str,
        cert_fingerprint: str | None = None,
        *,
        make_active: bool = True,
    ) -> None: ...

    def change_seed(self, old_seed: str, new_seed: str) -> Any: ...

    def pending_identity_dir(self, aid: str) -> Any: ...

    def list_pending_identity_dirs(self, aid: str) -> list[Any]: ...

    def save_pending_key_pair(self, pending_dir: Any, aid: str, key_pair: dict) -> None: ...

    def load_pending_key_pair(self, pending_dir: Any, aid: str) -> dict | None: ...

    def save_pending_cert(self, pending_dir: Any, cert_pem: str) -> None: ...

    def promote_pending_identity(self, pending_dir: Any, aid: str) -> Any: ...

    def discard_pending_identity(self, pending_dir: Any) -> None: ...

    def load_identity(self, aid: str) -> dict | None: ...

    def save_identity(self, aid: str, identity: dict) -> None: ...

    def list_identities(self) -> list[str]: ...

    def trust_root_dir(self) -> Any: ...

    def trust_root_bundle_path(self) -> Any: ...

    def save_trust_roots(self, trust_list: dict[str, Any], root_certs: list[dict[str, str]]) -> Any: ...

    def save_issuer_root_cert(self, issuer: str, cert_pem: str, fingerprint_sha256: str = "") -> Any: ...
