from __future__ import annotations


CERT_NOT_FOUND = "CERT_NOT_FOUND"
CERT_PARSE_ERROR = "CERT_PARSE_ERROR"
CERT_EXPIRED = "CERT_EXPIRED"
CERT_NOT_YET_VALID = "CERT_NOT_YET_VALID"
CERT_CHAIN_BROKEN = "CERT_CHAIN_BROKEN"
KEYPAIR_MISMATCH = "KEYPAIR_MISMATCH"
PRIVATE_KEY_PARSE_ERROR = "PRIVATE_KEY_PARSE_ERROR"

IDENTITY_CONFLICT = "IDENTITY_CONFLICT"
INVALID_AID_FORMAT = "INVALID_AID_FORMAT"
NETWORK_ERROR = "NETWORK_ERROR"
SERVER_ERROR = "SERVER_ERROR"

AGENTMD_NOT_FOUND = "AGENTMD_NOT_FOUND"
AGENTMD_PARSE_ERROR = "AGENTMD_PARSE_ERROR"
SIGNATURE_NOT_FOUND = "SIGNATURE_NOT_FOUND"
SIGNATURE_INVALID = "SIGNATURE_INVALID"
CERT_FINGERPRINT_MISMATCH = "CERT_FINGERPRINT_MISMATCH"

CERT_RENEWAL_FAILED = "CERT_RENEWAL_FAILED"
REKEY_FAILED = "REKEY_FAILED"
PRIVATE_KEY_REQUIRED = "PRIVATE_KEY_REQUIRED"

SIGNATURE_OPERATION_ERROR = "SIGNATURE_OPERATION_ERROR"
VERIFICATION_OPERATION_ERROR = "VERIFICATION_OPERATION_ERROR"
CERT_NOT_VALID = "CERT_NOT_VALID"
PRIVATE_KEY_NOT_VALID = "PRIVATE_KEY_NOT_VALID"

TRUST_ROOTS_INVALID = "TRUST_ROOTS_INVALID"


__all__ = [name for name in globals() if name.isupper()]
